version: '3.8'

services:
  v2ray-server:
    image: v2fly/v2fly-core:latest
    container_name: v2ray-server
    command: run -config /etc/v2ray/server.json
    ports:
      # Expose UDP port 8080 to the host machine (and the public internet)
      - "8080:8080/udp"
    volumes:
      # Mount the generated configs and certs as read-only for security
      - ./config/server.json:/etc/v2ray/server.json:ro
      - ./certs:/etc/v2ray/certs:ro
    restart: always

  v2ray-client:
    image: v2fly/v2fly-core:latest
    container_name: v2ray-client
    command: run -config /etc/v2ray/client.json
    ports:
      # IMPORTANT: Expose the SOCKS5 proxy ONLY on the host's loopback interface
      - "127.0.0.1:10808:10808/tcp"
    volumes:
      - ./config/client.json:/etc/v2ray/client.json:ro
    restart: always
    # This ensures the server container is started before the client
    depends_on:
      - v2ray-server